# Generated by Django 4.0.6 on 2022-07-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50, verbose_name='セラー名')),
                ('seller_url', models.URLField(verbose_name='セラーURL')),
                ('follow', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.URLField(verbose_name='商品画像URL')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('today_sold', models.PositiveIntegerField(verbose_name='今日の販売個数')),
                ('tomorrow_sold', models.PositiveIntegerField(verbose_name='昨日の販売個数')),
                ('d2_sold', models.PositiveIntegerField(verbose_name='2日前の販売個数')),
                ('d3_sold', models.PositiveIntegerField(verbose_name='3日前の販売個数')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='キーワード')),
                ('tag1', models.CharField(blank=True, max_length=10, null=True, verbose_name='サブカテゴリ')),
                ('category', models.CharField(blank=True, max_length=10, null=True, verbose_name='サブサブカテゴリ')),
                ('product_url', models.URLField(verbose_name='商品URL')),
                ('product_img', models.URLField(verbose_name='商品画像URL')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('sold_time', models.CharField(max_length=5, verbose_name='売り切れ時間')),
                ('seller_name', models.CharField(max_length=50, verbose_name='セラー名')),
                ('seller_url', models.URLField(verbose_name='セラーURL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
