# Generated by Django 4.0.6 on 2022-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='サブサブカテゴリ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='カテゴリー'),
        ),
    ]
