# Generated by Django 4.0.6 on 2022-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_product_tag2_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.PositiveIntegerField(default=1, verbose_name='キー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=100, verbose_name='商品価格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='sales',
            field=models.PositiveIntegerField(default=100, verbose_name='セラー売り上げ'),
            preserve_default=False,
        ),
    ]
