# Generated by Django 4.0.6 on 2022-07-26 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0006_remove_product_key_prodcutkey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdcutKey',
            new_name='ProductKey',
        ),
    ]
